[build]
rootDirectory = "backend"
buildCommand = "npm ci --only=production"
startCommand = "npm start"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
port = 8080
interval = 30
timeout = 10
