apiVersion: apps/v1
kind: Deployment
metadata:
  name: partytix-frontend
  namespace: partytix-staging
  labels:
    app: partytix-frontend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: partytix-frontend
  template:
    metadata:
      labels:
        app: partytix-frontend
        environment: staging
    spec:
      containers:
      - name: frontend
        image: partytix-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "staging"
        - name: NEXT_PUBLIC_API_URL
          value: "https://staging-api.partytix.com/v1"
        - name: NEXT_PUBLIC_SITE_URL
          value: "https://staging.partytix.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: partytix-frontend-service
  namespace: partytix-staging
  labels:
    app: partytix-frontend
spec:
  selector:
    app: partytix-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
