name: CD Pipeline

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test:all
      
    - name: Build application
      run: |
        npm run build
        cd backend && npm ci && npm run build
        
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment"
        # Add staging deployment commands here
        
    - name: Run smoke tests
      run: npm run test:smoke

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full test suite
      run: npm run test:full
      
    - name: Build application
      run: |
        npm run build
        cd backend && npm ci && npm run build
        
    - name: Deploy to production
      run: |
        echo "Deploying to production environment"
        # Add production deployment commands here
        
    - name: Run health checks
      run: npm run health:check
      
    - name: Notify deployment success
      run: |
        echo "Production deployment completed successfully"
